### ISSUE TITLE
Rebuild script

### ISSUE THREAD

**Issue by nicholasmello** [xonmello/arcade-build#4]
Quality of life, built script without /bin/bash at the end starting a new terminal session. Can go in /bin

**Comment by xonmello** [comment]
Functionality added 

https://github.com/xonmello/arcade-build/commit/9e9311d495e8f9cf3326169b8ca6eb87cde39f2c

**Comment by nicholasmello** [comment]
Functionality added 

https://github.com/xonmello/arcade-build/commit/9e9311d495e8f9cf3326169b8ca6eb87cde39f2c
